package com.zs;

public enum Section {
    ESSAI_DE_PERMEABILITE_IN_SITU,
    FOUILLES_DE_RECONNAISSANCE,
    RESULTATS_DES_ESSAIS_EN_LABORATOIRE,
    MODE_DE_FONDATION_SUR_SEMELLES_ISOLEES,
    MODE_DE_FONDATION_SUR_RADIER_GENERAL,
    REMARQUES_GENERALES_MODE_DE_FONDATION_SUR_SEMELLES_FILANTES_OU_ISOLEES,
    MODE_DE_FONDATION_SUR_SEMELLES_FILANTES,
    MODE_DE_FONDATION_SUR_SEMELLES_FILANTES_OU_ISOLEES,
    MODE_DE_FONDATION_SUR_PUITS,
    MODE_DE_FONDATION_SUR_PUITS_BUSES_OU_EN_MODE_TARIERE_CREUSE,
    MODE_DE_FONDATION_PROFOND_PAR_MICROPIEUX,
    MODE_DE_FONDATION_PROFOND_PAR_PIEUX,
    RENFORCEMENT_DE_SOL_PREALABLE_PAR_INCLUSION,
    COLONNES_BALLASTEES,
    DALLAGE,
    MITOYENNETE,
    VORIE,
    CONDITIONS_D_INFILTRATION_DES_EAUX_PLUVIALES_DANS_LE_SOL,
    FOUILLES_ARCHEOLOGIQUES,
}
